### ISSUE TITLE
SyntaxError: Unexpected token Q in JSON

### ISSUE THREAD

**Issue by cryptix** [ssbc/forked-systray#3]
```
SyntaxError: Unexpected token Q in JSON at position 0
    at JSON.parse (<anonymous>)
    at Interface.<anonymous> (/home/cryptix/ssb/patchbay/node_modules/forked-systray/lib/index.js:57:31)
    at emitOne (events.js:121:20)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
    at Interface._normalWrite (readline.js:424:12)
    at Socket.ondata (readline.js:141:10)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
```

Hrm.. this might be the case because I [unmanteld](https://github.com/ssbc/systrayhelper/commit/2626aa7e79381ea6b6f79e15f11adc8dc9b9923a) the sub-optimal _json as a single line_ handling on the helper side but not this one.

**Comment by cryptix** [comment]
Yup. There is `readline` in this module.

https://github.com/ssbc/forked-systray/blob/04aa6547cb31d1fb405270a4f3057fa351db4150/src/index.ts#L114

This is totally unnecessary and should be removed.

**Comment by cryptix** [comment]
The thinking might have been to unblock buffering but in that case I'd rather flush the writer on each side after writing than doing this.
